### ISSUE TITLE
Kontrola antiviru

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#11]
budou různé produkty minimálně Symantec, MS Defender.
**Skript musi zjistit aktulni virovou bazi techto produktu.**
Skript nevyhodnocuje zda je baze aktualni nebo ne
**Rezident běží ano/na**
**Byla provedena poslenid kontrola? výsledek pozitovní/negativní**

**Comment by lukaskarabec** [comment]
kontrola AV rozpracována ve skriptu checkSEP

**Comment by lukaskarabec** [comment]
LuKa: úprava na zjištění aktuální verze, bez vyhodnocování

**Comment by marrensie** [comment]
detekce instalovaneho AV + sber dat

**Comment by lukaskarabec** [comment]
@marrensie  vyřešil... uzavírám
