### ISSUE TITLE
Zakladni navrh GUI pro AVAS

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#18]
Zakladni navrh jak bude vypadat GUI pro AVAS

**Comment by lukaskarabec** [comment]
tužka papír nebo rovnou c# winform? :)

**Comment by caithaml** [comment]
Asi bych to udelal primo ve winform dle puvodniho AVASU

**Comment by lukaskarabec** [comment]
Prosím o zkontrolování GUI rozhraní ICWSC - zda takto vyhovuje... ICWSC/GUI_AVAS/GUI_AVAS/bin/Release/ 
exe soubor

**Comment by caithaml** [comment]
Presunuto do AVAS
