### ISSUE TITLE
Otestovani ICWSC

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#19]
Otestovat nove ICWSC ke konci Milestone1 v ramci bezpecnostnich testu

**Comment by caithaml** [comment]
Otestovano na Win 10 a 2016 serveru. Po oprave chyb a pridani dalsich funkci probehne test znovu.
Test musi byt proveden na techto OS:
Win 10 64 a 32
Win XP
2003 R2 32 a 64
2008 R2 64
2012 R2 64
2016 64

**Comment by lukaskarabec** [comment]
je potřeba provést test znovu
