### ISSUE TITLE
Upravit kontrolu disku

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#22]
Kontrolu disku upravit nasledovne:

Aktualni stav:
C_Label              : 
C_Size               : 127456505856
C_Free               : 22775803904
C_Serial             : 9066E98F
D_Label              : DATA
D_Size               : 499971518464
D_Free               : 159191453696
D_Serial             : 82FE7CF2
N_Label              : 
N_Size               : 
N_Free               : 
N_Serial             : 

Takhle je to nevyhovujici. Je to v moc objektech. Dal bych to do jednoho a pouzil napr. tuto funkci:

http://binarynature.blogspot.cz/2010/04/powershell-version-of-df-command.html

**Comment by lukaskarabec** [comment]
přidán doporučený skript - výpis disků je prováděn
