### ISSUE TITLE
Noteproperty s :

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#25]
Vsude kde je ve skriptu za nazvem Noteproperty znak **:** prosim o smazani. Nepouzivej **:** 
Napr. 
$hash.Pevne_disky
musim dat do uvozovek aby to fungovalo
$hash.'Pevne_disky:'

**Comment by lukaskarabec** [comment]
Výsledek nepoužívat : ? (dvojčtečky)

**Comment by lukaskarabec** [comment]
opraveno
