### ISSUE TITLE
Vypis IP 

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#26]
https://github.com/caithaml/ICWSC/blob/e6497500420d75e97dd5574f813900fbfe7abe94/ICWSC.ps1#L317
Co to nahradit get-netipconfiguration pokud je tento prikaz podporovan aspon na 2008 R2? Pokud ne tak musime vymyslet jeste neco jineho protoze v aktualnim stavu mi to na PC vyhodi pouze IPv6 adresu.

**Comment by lukaskarabec** [comment]
opraveno
