### ISSUE TITLE
Sjednoceni nazvu

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#28]
Pouzivame v nazvu vysledku:
N
Not Installed
missing
Nezname
0
prazdne pole
Chce to nejak sjednotit at se to pak dobre filtruje. ENG nebo CZ?

Stejne tak v nazvu NoteProperty mame nekdy CZ a nekdy ENG nazev. To uz se tahne z minulosti. Pouzil bych asi vsude ENG co ty na to?

**Comment by lukaskarabec** [comment]
Hodnoty jako N , 2 atd jsem nechal z původního skriptu beze změny... Všude teda budu měnit na ENG?

**Comment by caithaml** [comment]
Vsude ENG

**Comment by lukaskarabec** [comment]
OK

**Comment by lukaskarabec** [comment]
sjednoceny názvy - vše ENG
