### ISSUE TITLE
Vyhodit Endpoint

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#29]
https://github.com/caithaml/ICWSC/blob/e6497500420d75e97dd5574f813900fbfe7abe94/ICWSC.ps1#L186

Vyhod pls Endpoint_icon, service a id. Uz se to nepouziva

**Comment by lukaskarabec** [comment]
$hash | add-member Noteproperty Endpoint_icon $(if (test-path 'c:\Program Files\tivoli\lcf\bin\w32-ix86\mrt\upgrade\lcfd.exe') { Write-Output '4.1'} else {Write-Output 'Not Installed'})
$hash | add-member Noteproperty Endpoint_service $(if (test-path 'c:\Program Files\tivoli\lcf\bin\w32-ix86\mrt\lcfd.exe') { Write-Output '4.1'} else {Write-Output 'Not Installed'})
$hash | add-member Noteproperty Endpoint_id $(Get-Content 'C:\Program Files\tivoli\lcf\dat\1\lcf.id'| Select-Object -First 1)


odstraněno
