### ISSUE TITLE
Applocker events

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#31]
Pridal bych jeste chybove hlasky z applocker logu za poslednich $limitlogy dni. Pokud bude spustene nejaka nepovolena apka tak to bude v tomto logu. Ty logy jsou 4 a jsou v Microsoft- Windows -Applocker. Pro kazdy vytvor zvlasnit noteproperty

**Comment by lukaskarabec** [comment]
Oficiální název logu (z Get-Winevent -list ?? )  Díky :)

**Comment by caithaml** [comment]
https://github.com/caithaml/ICWSC/blob/b58e1d86a26f324a8fc7ba8d090b2c7db19a5b79/ICWSC.ps1#L496-L518
