### ISSUE TITLE
SEP

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#35]
Na 2016 serveru kde neni a nikdy nebyl sep je vypis takovyhle:
SEPRegVersion        : NotInstalled
SEPVersion           : 
SEPService           : 
SEPClientType        : 0
SEPPolicyMode        : 
SEPInfected          : **2**
SEPDefinitions       : missing

Nejak bych to sjednotil. u neceho je 0 u neco missing a u neceho NotInstalled. Dosti divne je SEPInfected:2

**Comment by lukaskarabec** [comment]
Původní kod není můj, zjistim

**Comment by lukaskarabec** [comment]
### test priznaku Infected (pouze SEP 12.x)
# 0 = OK
# 1 = Infected
# 2 = neni instalovana verze 12 = hodnota neexistuje


viz komentář v kodu

**Comment by lukaskarabec** [comment]
oveření SEP řešeno také ve zkušebním skriptu checkSEP

**Comment by lukaskarabec** [comment]
dojde ke změně hlášky
