### ISSUE TITLE
Group Policy 

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#36]
https://github.com/caithaml/ICWSC/blob/e6497500420d75e97dd5574f813900fbfe7abe94/ICWSC.ps1#L27

Dela tohle jeste vubec neco? Pustil jsem to na Win10 a 2016 serveru a nikde ta hodnota neni

**Comment by lukaskarabec** [comment]
Netuším, nepsal jsem.. musím se podívat

**Comment by caithaml** [comment]
Opraveno. Skript zjistoval jmeno aktualniho DC
