### ISSUE TITLE
Protect

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#37]
https://github.com/caithaml/ICWSC/blob/e6497500420d75e97dd5574f813900fbfe7abe94/ICWSC.ps1#L183

Kdyz neni naistalovan tak bych cekal, ze to vyhodi: **Not Installed**

**Comment by lukaskarabec** [comment]
přidám - původní není můj kod, nevím ani jestli jsou cesty správně :)

**Comment by lukaskarabec** [comment]
opraveno
