### ISSUE TITLE
Prehled nainstalovaneho sw

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#42]
Vypis nainstalovaneho sw. Asi bude stacit pole stringu. **Nesmi** byt pouzito WMI win32_product
Asi nejlepsi bude dir registru uninstall 
Viz https://blogs.technet.microsoft.com/heyscriptingguy/2011/11/13/use-powershell-to-quickly-find-installed-software/

**Comment by lukaskarabec** [comment]
přidáno klasické winform app + UWP

**Comment by lukaskarabec** [comment]
UWP jen pro WIN8 a vyšší
