### ISSUE TITLE
win32_ nutne opravy

### ISSUE THREAD

**Issue by lukaskarabec** [caithaml/ICWSC#46]
`$hash | Add-Member Noteproperty BIOS $((Get-WmiObject win32_bios).Version + ' | ' + (Get-WmiObject win32_bios).Name)
$hash | Add-Member Noteproperty BIOS_date (Get-WmiObject win32_bios).ConvertToDateTime((Get-WmiObject win32_bios).ReleaseDate)`

**Comment by caithaml** [comment]
Co tam chces opravit?

**Comment by lukaskarabec** [comment]
ok
