### ISSUE TITLE
Get-GPResultantSetofPolicy

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#48]
https://github.com/caithaml/ICWSC/blob/7c1bd69464ed3ac559d1351d11a00134900a9b74/ICWSC.ps1#L30
**Get-GPResultantSetofPolicy** 
CMDlet nefunguje jen tak sam o sobe. Je nutne mu zadat parametry, ktere urci jaky rsop bude vytvoren (HTML, XML) a kam bude ulozen. 
- Je mozne ulozit XML nebo HTML do NoteProperty primo do $hash skrze napr. nejaky temp soubor?
- pozor funguje pouze na Server edicich

**Comment by caithaml** [comment]
Ve skriptu jsem radek zatim zakomentoval

**Comment by lukaskarabec** [comment]
@caithaml  zakomentoval - rozhodne @caithaml

**Comment by lukaskarabec** [comment]
Opraveno - nutno zvolit  případně cestu - default ./
