### ISSUE TITLE
SEP kontrola

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#50]
https://github.com/caithaml/ICWSC/blob/936a44ee28f4df7aa80f292e4489d5487e55b5dc/ICWSC.ps1#L409-L436
Ty me znicis ty kluku :)
ICWSC nema testovat zda je neco aktulani nebo ne. To udela az AVAS nebo cokoliv dalsiho. Prosim prepracovat/zrusit. Nechceme zadne vyhodnocovani v tomto skriptu. Pouze sber dat

**Comment by lukaskarabec** [comment]
Neověřeno - nemám nainstálováno 🔢
