### ISSUE TITLE
Uprava vyslednych dat

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#51]
https://github.com/caithaml/ICWSC/blob/936a44ee28f4df7aa80f292e4489d5487e55b5dc/ICWSC.ps1#L438-L464

Prosim uprav to tak aby bylo rozhodovani OS udelano jako tady #9 
Vysledek preved na MB
Zaokrouhlit na cela cisla (oboji je uz pouzito ve scriptu)

**Comment by lukaskarabec** [comment]
nutno ověřit k 04102017-1113
