### ISSUE TITLE
Vysledny soubor je moc velky

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#57]
Po vyexportovani $hash zabira vysledne xml na Win10 stanici 82MB. Pokud udelam xml, ktere nebosahuje logy tak je vysledny soubor 68MB. Oboji je strasne moc. Budeme to muset vyrazne snizit.

Najit NoteProperty, ktere zabiraji nejvice mista
Mame tam nejake informace opakovane?

**Comment by lukaskarabec** [comment]
Prostor zabírají moc podrobné informace o PC, certifikátech atd.

**Comment by caithaml** [comment]
Kolik to je cca MB?

**Comment by lukaskarabec** [comment]
opraveno - nyní cca 6,5MB
