### ISSUE TITLE
Chyba detekce LAPS

### ISSUE THREAD

**Issue by davidkejr** [caithaml/ICWSC#58]
Opravit vyhledávaný klíč v registru Uninstall pro 32-bit verzi. Doplnit detekci LAPS v 64-bit verzi.

32-bit:
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{937A3762-F1D5-45F3-AA20-F7C5CBA7FBAC}

64-bit:
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EA8CB806-C109-4700-96B4-F1F268E5036C}

**Comment by lukaskarabec** [comment]
není opraveno k 04102017-1111

**Comment by lukaskarabec** [comment]
Opraveno 04-10-2017
