### ISSUE TITLE
Detekce DSlog nefunguje

### ISSUE THREAD

**Issue by davidkejr** [caithaml/ICWSC#60]
Detekce služby DSLog nefunguje (a ani takto dle mého názoru nemůže).

V detekci služeb obecně doporučuji používat plný zápis parametrů příkazu Get-Service.

**Comment by lukaskarabec** [comment]
K 04102017-1110 neověřena funkčnost, nutno zkontrolovat

**Comment by lukaskarabec** [comment]
opraveno
