### ISSUE TITLE
Noteproperty Installed_Apps

### ISSUE THREAD

**Issue by davidkejr** [caithaml/ICWSC#61]
Chybné zacílení registru Uninstall.

**Comment by caithaml** [comment]
$hash | Add-Member NoteProperty Installed_Apps (Get-ItemProperty -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*)
Opraveno

**Comment by caithaml** [comment]
https://github.com/caithaml/ICWSC/blob/c785d00be03949eb4d3f9e371a0e598639a1d464/ICWSC.ps1#L547
