### ISSUE TITLE
Zjisteni verze OS

### ISSUE THREAD

**Issue by caithaml** [caithaml/ICWSC#9]
Na zacatku skriptu zjistit:
1) verze OS
2) architektura
3) build

a podle toho spustet testy

**Comment by lukaskarabec** [comment]
Zjištění proběhne hned na začátku běhu skriptu

**Comment by lukaskarabec** [comment]
zjištění os ano, úprava všech skriptů dle OS nedokončena

**Comment by caithaml** [comment]
#Operating system	Version number - seznam prevzat z Microsoft webu - napoveda pro urcovani verze OS ve skriptech
#Windows 10	10.0*
#Windows Server 2016	10.0*
#Windows 8.1	6.3*
#Windows Server 2012 R2	6.3*
#Windows 8	6.2
#Windows Server 2012	6.2
#Windows 7	6.1
#Windows Server 2008 R2	6.1
#Windows Server 2008	6.0
#Windows Vista	6.0
#Windows Server 2003 R2	5.2
#Windows Server 2003	5.2
#Windows XP 64-Bit Edition	5.2
#Windows XP	5.1
#Windows 2000	5.0


### detekce verze OS
# 1 = Windows XP x32 (vychozi)
# 2 = Windows Server 2003 R2 x32
# 3 = Windows Server 2003 R2 x64
# 4 = Windows Server 2008 R2 x64
### LuKa - pridani dalsich OS
# 5 = Windows 7
# 6 = Windows 8
# 7 = Windows 8.1
# 8 = Windows 10
# 9 = Windows Server 2012 R2
# 10 = Windows Server 2016

**Comment by caithaml** [comment]
Prepracoval jsem zjisteni OS na:
**$System = $win32_OperatingSystem**
Zjisteni OS se ted bude delat takto:
**Napr Windows 10 Pro:**
if ($System.caption -eq "Microsoft Windows 10 Pro") {%provedtest%}
**Vsechny Server OS:**
if ($System.caption -like "*Server*") {%provedtest%}

**Comment by caithaml** [comment]
**Architektura**
if ($System.OSArchitecture -eq "64-bit") {%provedtest%}
